version: "3"
services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test_springboot
            MYSQL_USER: lequo
            MYSQL_PASSWORD: 123456
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 3307:3306
